spring.application.name=AI_Assistant

server.port=8082

#Gemini Api key
spring.ai.vertex.ai.gemini.project-id=${GEMINI_PROJECT_ID}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash-001

spring.ai.image.options.n=1
spring.ai.image.options.width=1024
spring.ai.image.options.height=1024

#Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest
spring.ai.ollama.init.pull-model-strategy=when_missing

#Stability AI
spring.ai.stabilityai.api-key=${STABILITYAI_API_KEY}
spring.ai.stabilityai.image.options.model=stable-diffusion-xl-1024-v1-0

#Hugging Face
spring.ai.zhipuai.api-key=<zhipuai-api-key>
spring.ai.zhipuai.image.options.model=CogView-3

logging.level.org.springframework.ai.chat.client.advisor=debug

#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringAiChatMemory
spring.datasource.username=lakshay
spring.datasource.password=Python043@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.chat.memory.repository.jdbc.initialize-schema=always